name: innvestigate
channels:
  - conda-forge
  - base
dependencies:
  - pip
  - python=3.7
  - keras=2.2.4
  - tensorflow=1.13
  # - tensorflow-gpu=1.13
  # - cudatoolkit=9.0
  - pandas=0.25
  - numpy=1.18
  - matplotlib
  - seaborn
  - ipykernel
  - pip:
    - git+https://github.com/albermax/innvestigate.git@develop